files:
  include: 'client/**/*.s+(a|c)ss'

rules:
  empty-line-between-blocks: 0
  property-sort-order: 0
  no-color-keywords: 0
  nesting-depth:
    - 1
    - max-depth: 5
  no-ids: 0
  no-important: 0
  force-pseudo-nesting: 0
  single-line-per-selector: 0
  no-color-literals: 0
  placeholder-in-extend: 0
