# Travis config
language: node_js
# Versions
node_js:
  - stable
  - "7"
  - "6"
  - "6.1.0"
  - "5"
  - "4"
  - "4.4"
# services
services:
  - mongodb
# ENV
env:
  global:
    - NODE_ENV=development
# Scripts
install: npm install
script: npm test
after_script: npm run coveralls
