###
# IMPORTANT! IMPORTANT! IMPORTANT! IMPORTANT!
# 1. Never checkout this file into a public repositary.
#    Doing so may put the security and the users of your bedel server at risk.
# 2. If you find this file in a public repo,
#    it is probably the example file (secrets.example.yml)
# 3. This file stores oauth keys, session secrets and
#    db access usernames + passwords.
# 3. TREAT EVERYTHING IN THIS FILE AS A PASSWORD!
###

# Session keys
# For express session
session_secret: $1h67UjiufhieuwhJOEJ-Bedel-SerVer-83283282920

# OAuth
# See docs/oauth/providers.md for providers
oauth:
  # GitHub stratergy
  github:
    # Change this line to true to enable github authentication
    enabled: false
    # Client id & secret
    id: ID_HERE
    secret: SECRET_HERE
