#!/usr/bin/env node
// Script to make dirs for bedel
const mkdirp = require('mkdirp');
// Dirs
const dirs = [
  'tmp',
  'tmp/cache'
];

console.log(`==> Creating directories for bedel...`);

// Make each one
dirs.forEach((item) => {
  mkdirp(item, (err) => {
    if (err) {
      throw err;
    } else {
      console.log(`==> Created dir ${item}`);
    }
  });
});
